### ISSUE TITLE
not work with aiogram3.5.0

### ISSUE THREAD

**Issue by mertwec** [daniilshamraev/aiogram-inline-paginations#6]
ImportError: cannot import name 'Text' from 'aiogram.filters' (/media/work/Disk/GoITeens_tech/1_semestr/Telegram_bot/telegram_bot_hint/.venv/lib/python3.10/site-packages/aiogram/filters/__init__.py)
